sudo rm /usr/share/applications/qv4l2.desktop
sudo rm /usr/share/applications/qvidcap.desktop
sudo rm /usr/share/applications/assistant.desktop
sudo rm /usr/share/applications/avahi-discover.desktop
sudo rm /usr/share/applications/java-java-openjdk.desktop
sudo rm /usr/share/applications/jshell-java-openjdk.desktop
sudo rm /usr/share/applications/jconsole-java-openjdk.desktop
sudo rm /usr/share/applications/qdbusviewer.desktop
sudo rm /usr/share/applications/linguist.desktop
sudo rm /usr/share/applications/designer.desktop
sudo rm /usr/share/applications/bssh.desktop
sudo rm /usr/share/applications/bvnc.desktop
